### PR TITLE
add host extension for yandex bot

### PR DESCRIPTION
**Pull request by worldofsites**

### CODE REVIEW

**Comment by karl-sjogren** [comment]
I can't find any documentation for this field on the Yandex support pages.

https://yandex.com/support/webmaster/controlling-robot/robots-txt.html

Can you point me to where it specifies this field?

**Comment by worldofsites** [comment]
@karl-sjogren 
This is a recently deprecated directive, but it is still valid and used on some sites.
Strange, but it seemed to me that I saw it on the Yandex webmaster pages quite recently.
https://stackoverflow.com/a/49524236
https://yoast.com/ultimate-guide-robots-txt/#host-directive

**Comment by karl-sjogren** [comment]
Since it has been completely removed from their support pages I wouldn't say that it is a valid field anymore. That it is used on some sites is probably because they haven't bothered to remove it (or don't know that it has been removed).

I used the Wayback Machine to check this page and even in february of 2019 it was gone.

https://web.archive.org/web/20190207032802/https://yandex.com/support/webmaster/controlling-robot/robots-txt.html

I had to go all the way back to novemberof 2017 to find any information about it (thouch they have nothing saved for 2018 it seems).

https://web.archive.org/web/20171120030340/https://yandex.com/support/webmaster/controlling-robot/robots-txt.html

Seeing as they haven't promoted it for more then a year I see no reason to add support for it in this library.

**Comment by worldofsites** [comment]
Fair enough. Thanks!

**Pull request closed without merging**
